### ISSUE TITLE
Ore Eater and Fortune/Silktouch (Is this WAI?)

### ISSUE THREAD

**Issue by MatthewVillablanca** [MrCrayfish/Enchantable#14]
Ore eater and fortune cannot both be applied to a pickaxe. This limits Ore Eater's capabilities since most players would prefer to mine each ore with fortune rather than mine all of them at once with OE. This means you would only use OE to mine gold_ore and iron_ore

**Comment by MrCrayfish** [comment]
Changed in https://github.com/MrCrayfish/Enchantable/commit/3936b2404c40c0daae459275ae23898f3d2d19ba
